language: node_js
sudo: required
services:
  - docker
node_js:
  - "6.10"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt remove docker
  - curl -fsSL https://get.docker.com/ | sh > /dev/null
install:
  - npm install --silent
script:
  - npm run gulp all-non-e2e
  - npm run gulp lint
after_success:
  - npm run gulp coverage
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=desarrolloleutwylerdubor/scraaaam
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export IMAGE_NAME=$REPO:$TRAVIS_COMMIT
  - docker build -f Dockerfile -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $REPO:$TAG
  - docker tag $IMAGE_NAME $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $IMAGE_NAME
  - docker push $REPO:$TAG
  - docker push $REPO:travis-$TRAVIS_BUILD_NUMBER

