language: node_js
sudo: required
services:
  - docker
node_js:
  - "6.10"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt remove docker
  - curl -fsSL https://get.docker.com/ | sh > /dev/null
install:
  - npm install --silent
script:
  - npm run gulp lint
  - npm run gulp all-non-e2e
  - npm run gulp e2e-test
after_success:
  - npm run gulp coverage
  - npm run gulp docker-push
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run gulp niffy-test; fi
