version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    command: "--smallfiles --logpath=/dev/null"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        app_port: 3002
    ports:
      - "3002:3002"
    environment:
      MONGO_URL: 'mongodb://mongo/projects'
      APP_PORT: 3002
